apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    component: ftps
spec:
  selector:
    component: ftps
  ports:
  - name: ftps-21
    port: 21
    protocol: TCP
    targetPort: 21
  - name: ftps-30001
    port: 30001
    protocol: TCP
    targetPort: 30001
  selector:
    component: ftps
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    component: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      component: ftps
  template:
    metadata:
      labels:
        component: ftps
    spec:
      containers:
      - name: ftps
        image: ft_services/ftps
        ports:
        - containerPort: 21
        - containerPort: 30001
        imagePullPolicy: Never