apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: influxdb
  template:
    metadata:
      labels:
        component: influxdb
    spec:
      containers:
        - name: influxdb
          image: influxdb_ft-services:latest
          ports:
            - containerPort: 8086

