apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    component: nginx
spec:
  selector:
    component: nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    component: nginx
spec:
  selector:
    matchLabels:
      component: nginx
  template:
    metadata:
      labels:
        component: nginx
    spec:
      containers:
      - name: nginx
        image: ft_services/nginx
        imagePullPolicy: Never
        livenessProbe:
          periodSeconds: 5
          initialDelaySeconds: 10
          exec:
            command:
            - /bin/sh
            - /liveness.sh
