apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    component: mysql
spec:
  type: ClusterIP
  selector:
    component: mysql
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP