apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    component: phpmyadmin
spec:
  selector:
    matchLabels:
      component: phpmyadmin
  template:
    metadata:
      labels:
        component: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: ft_services/phpmyadmin
        ports:
        - containerPort: 5000
        imagePullPolicy: Never