apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    component: phpmyadmin
spec:
  selector:
    component: phpmyadmin
  ports:
    - name: pma-port
      protocol: TCP
      port: 5000
      targetPort: 80
  type: LoadBalancer