apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    component: phpmyadmin
spec:
  selector:
    component: phpmyadmin
  ports:
    - name: pma-port
      protocol: TCP
      port: 5000
      targetPort: 80
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    component: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      component: phpmyadmin
  template:
    metadata:
      labels:
        component: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: ft_services/phpmyadmin
        ports:
        - containerPort: 5000
        imagePullPolicy: Never