apiVersion: v1
kind: Service
metadata:
  name: grafana
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    component: grafana
spec:
  selector:
    component: grafana
  ports:
    - name: grafana-port
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    component: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      component: grafana
  template:
    metadata:
      labels:
        component: grafana
    spec:
      containers:
      - name: grafana
        image: ft_services/grafana
        ports:
        - containerPort: 3000
        imagePullPolicy: Never